/* eslint-disable */
/**
 * Stub generated by `screeen` setup. This file will be overwritten when you
 * run `npx convex dev`. Until then it provides loose typing so the project
 * can build.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const _api: any;
export declare const api: any;
export declare const internal: any;
